[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "/Users/dean/rxv6/user/i686-rxv6-user.json"

[target.'cfg(all())']
rustflags = ["-C", "link-arg=-T/Users/dean/rxv6/user/linker.ld"]
json-target-spec = true
