#!/usr/bin/env python3
"""Generate embedded_tests.rs from compiled ELF binaries."""

import os
import sys

BUILD_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "build")
OUTPUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "embedded_tests.rs")
KERNEL_OUTPUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                              "..", "src", "userprog", "embedded_tests.rs")

# List of (elf_file, const_name, description)
TESTS = [
    ("test_minimal.elf", "TEST_MINIMAL",
     'Minimal test: writes "Hello from user mode!" to stdout and exits(0). Raw syscalls.'),
    ("args.elf", "TEST_ARGS",
     "Args test: prints argc/argv. Uses Pintos libc + test framework."),
    ("halt.elf", "TEST_HALT",
     "Halt test: calls halt() syscall."),
]


def elf_to_rust_array(data, const_name, description):
    lines = []
    lines.append(f"/// {description}")
    lines.append(f"/// ELF binary, {len(data)} bytes")
    lines.append(f"pub const {const_name}_ELF: &[u8] = &[")
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_vals},")
    lines.append("];")
    return "\n".join(lines)


def main():
    sections = []
    sections.append("// Auto-generated by user/gen_embed.py - do not edit manually")
    sections.append("// Contains embedded Pintos user test ELF binaries for RustOS")
    sections.append("//")
    sections.append("// Regenerate with: cd user && make embed")
    sections.append("")

    found_any = False
    for elf_file, const_name, desc in TESTS:
        path = os.path.join(BUILD_DIR, elf_file)
        if not os.path.exists(path):
            print(f"  Skipping {elf_file} (not found)")
            continue

        with open(path, "rb") as f:
            data = f.read()

        # Verify ELF magic
        if data[:4] != b"\x7fELF":
            print(f"  WARNING: {elf_file} is not a valid ELF file, skipping")
            continue

        sections.append(elf_to_rust_array(data, const_name, desc))
        sections.append("")
        found_any = True
        print(f"  Embedded {elf_file} ({len(data)} bytes) as {const_name}_ELF")

    if not found_any:
        print("ERROR: No ELF files found. Run 'make all' first.")
        sys.exit(1)

    content = "\n".join(sections)

    # Write to user/ directory
    with open(OUTPUT, "w") as f:
        f.write(content)
    print(f"\nGenerated {OUTPUT}")

    # Also copy to kernel source
    os.makedirs(os.path.dirname(KERNEL_OUTPUT), exist_ok=True)
    with open(KERNEL_OUTPUT, "w") as f:
        f.write(content)
    print(f"Copied to {KERNEL_OUTPUT}")


if __name__ == "__main__":
    main()
